modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="minecraft_live_arena"
version="${file.jarVersion}"
displayName="Minecraft Live Arena"
description='''Arena por rondas para viewers de TikTok Live.'''

[[dependencies.minecraft_live_arena]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraft_live_arena]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
